[features]
resolution = true
skip-lint = false

[programs.localnet]
freight_escrow = "Fn1eqswyWzygRwt83wwuGycqUQvUFmPDoMTGB3oeaYwx"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
